mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/testapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.TaskListView.as_view(), name='home'),
    path('task/<slug:slug>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('add_task/', views.AddTaskView.as_view(), name='add_task'),
    path('edit_task/<slug>/', views.EditTaskView.as_view(), name='edit_task'),
    path('delete_task/<slug>/', views.DeleteTaskView.as_view(), name='delete_task'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('policy/', views.PolicyPageView.as_view(), name='policy'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
]

mysite/testapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, User, UserManager

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _


STATUS = (
    (0,"Empty"),
    (1,"Occuped")
)

class Task(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='testapp_tasks')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    parking_lot_number = models.IntegerField(unique=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

mysite/testapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db.models import fields
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
from .models import *
from icecream import ic
from .helpers import AccessResolver


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(
        label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(
        attrs={'class': 'form-input'}))

    CHOICES = ((1, 'Менеджер'), (0, 'Работник'),)
    is_stuff = forms.CharField(widget=forms.Select(choices=CHOICES))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'is_stuff')

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.is_staff = self.cleaned_data['is_stuff']
        if commit:
            user.save()
        return user


class AddTaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].empty_label = "Автор не указан"
        self.fields['status'].empty_label = "Publish"

    title = forms.CharField(
        label='Заголовок', widget=forms.TextInput(attrs={'class': 'form-input'}))

    text = forms.CharField(
        label='Примечание', widget=forms.Textarea(attrs={'class': 'input-text-area'}))

    class Meta:
        model = Task
        fields = ('title', 'text', 'author', 'status',
                  'slug', 'parking_lot_number')

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Слишком длинное описание(>200 символов)')

        return title

class MyForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'author', 'status',
                  'slug', 'parking_lot_number')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(
        label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(
        widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    # capatcha = CaptchaField()

mysite/testapp/views.py
from django.http.response import HttpResponseNotAllowed
from django.views import generic
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Task
from .utils import *
from django.shortcuts import redirect
from django.contrib.auth import logout

from .forms import *
from .models import *
from .utils import *


class TaskListView(PostListMixin, generic.ListView):
    queryset = Task.objects.order_by('-created_on')
    template_name = 'index.html'


class TaskDetailView(PostDetailMixin, generic.DetailView):
    model = Task
    template_name = 'task_detail.html'


class AddTaskView(AccessMixin, CreateView):
    form_class = AddTaskForm
    template_name = 'add_task.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        if AccessMixin().get_access_by_request(self.request):
            form.save(commit=False)
            return super(AddTaskView, self).form_valid(form)
        else:
            return HttpResponseNotAllowed('Only for admin')


class EditTaskView(UpdateView):
    model = Task
    fields = '__all__'
    template_name = 'edit_task.html'
    success_url = reverse_lazy('home')


class DeleteTaskView(DeleteView):
    model = Task
    template_name = 'delete_task.html'
    success_url = reverse_lazy('home')


class AboutPageView(TemplateView):

    template_name = 'about.html'


class PolicyPageView(TemplateView):
    template_name = 'policy.html'


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('home')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

mysite/testapp/templates/about.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .custom-padding-top-2 {
        padding-top: 2%;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white">Просто тестовое задание</h3>
                    <h5 class="text-light">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A, cum</p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                        Enim vel fuga corporis rem quo doloribus incidunt similique, 
                        unde non recusandae necessitatibus soluta voluptatibus id modi 
                        ipsam consectetur numquam beatae dolore rerum, eum praesentium! 
                        Autem voluptatibus atque fuga non eaque repellat, neque aliquid dolor, 
                        at odit dicta beatae aspernatur labore tempore.
                    </h5>
                </div>
            </div>
        </div>
    </div>
</header>
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left custom-padding-top-2">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-dark">Читать ...</a>
                </div>
            </div>
            {% endfor %}
            {% block footer %} {% include 'footer.html' %} {% endblock footer %}
        </div>
    </div>
</div>
{%endblock%}

mysite/testapp/templates/add_task.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Забронировать место</button>
</form>

{% endblock %}

mysite/testapp/templates/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <link rel"stylesheet" href = "{% static 'script.css' %}">
    <head>
        <title>Blog site</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
        <script src="{% static '/js/jquery.js' %}"></script>
        <script src="{% static '/js/script.js' %}"></script>
    </head>

    <body>
        <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #3e3e3e;
            overflow-x:hidden
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-dark {
            color: #fff;
            background-color: #191919;
            border-color: #191919;
        }
        .masthead {
            background: #3e3e3e;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #191919;
            padding-top: 10px;
        }
        .cbutton{
            font-size:24px; 
            background-color:#cbcccd;
            border-radius:10px;
            padding-left:8px;
            padding-right:8px
        }
        a {
            color: black;
            text-decoration: none;
        }
        a:hover {
            color: black;
            text-decoration: none;
        }
    </style>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand cbutton" href="{% url 'home' %}">
                Главная</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                {% if request.user.is_staff %}
                    <a class="trigger_popup_fricc ">Изменить место</a>
                    <div class="hover_bkgr_fricc">
                        <span class="helper"></span>
                        <div>
                            {% for task in task_list %}
                            <div class="card mb-4">
                            <a href="{% url 'edit_task' task.slug %}">
                                <div class="card-body">
                                    <h2 class="card-title">{{ task.title }}</h2>
                                    <p class="card-text text-muted h6">{{ task.author }} | {{ task.created_on}} </p>
                                    <br>
                                    <a href="{% url 'task_detail' task.slug  %}" class="btn btn-dark">Открыть</a>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                            <p>Выберите место для изменения</p>
                        </div>
                    </div>  
                {% endif %}



                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">

                        {% if request.user.is_authenticated %}
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="/add_task">Забронировать место</a>
                        </li>    
                        {% endif %}

                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="/about">О проекте</a>
                        </li>
                        
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#"></a>
                        </li>

                        {% if request.user.is_authenticated %}
                        <li class="nav-link text-black font-weight-bold"> {{user.username}} | <a href="{% url 'logout' %}">Выйти</a></li>
                        {% else %}
                        <li class="nav-link text-black font-weight-bold"><a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a></li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
    </body>
</html>

mysite/testapp/templates/delete_task.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">{% csrf_token %}
    <p style='color:white;'>Очистить бронь парковочного места №: "{{ object.parking_lot_number }}"?</p>
    <input type="submit" value="Да,">
</form>

{% endblock %}

mysite/testapp/templates/edit_task.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Изменить</button>
    <a href="{% url 'delete_task' task.slug  %}" class="btn btn-danger">Удалить место</a>
</form>

{% endblock %}

mysite/testapp/templates/footer.html
{% block footer %}

<footer class="py-3 bg-grey">
    <p class="m-0 {{ footer_color }} text-center ">Copyright &copy; Site by EMWD</p>
</footer>

{% endblock footer %}

mysite/testapp/templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .custom-padding-top-2 {
        padding-top: 2%;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white">Приложение для бронирования парковочных мест </h3>
                    <p class="text-light">Какая-то информация</p>
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        {% if request.user.is_authenticated %}
  
        <div class="col-md-8 mt-3 left custom-padding-top-2">
            {% for task in task_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ task.title }}</h2>
                    <p class="card-text text-muted h6">{{ task.author }} | {{ task.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <p class="card-text">Номер парковочного мета: №{{task.parking_lot_number}}</p>
                    <p class="card-text">Время создания: {{task.created_on}}</p>
                    <a href="{% url 'task_detail' task.slug  %}" class="btn btn-dark">Открыть</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
        {% endif %}
    </div>
</div>
{% block footer %} {% include 'footer.html' %} {% endblock footer %}
{%endblock%}

mysite/testapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post" class='form'>
    {% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button class='form-button' type="submit">Войти</button>
</form>

{% endblock %}

mysite/testapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Регистрация</button>
</form>

{% endblock %}

mysite/testapp/templates/sidebar.html
{% comment %} {% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right custom-padding-top-2">
<div class="card my-4">
        <h5 class="card-header">Источники</h5>
    <div class="card-body">
        <p class="card-text"> Тут описаны источники, которые были использованы для созданяи платформы </p>
        <a href="https://docs.djangoproject.com/"
           class="btn btn-dark">Перейти</a>
    </div>
</div>
</div>

{% endblock sidebar %} {% endcomment %}

mysite/testapp/templates/task_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-16 card mb-10 p-3 mt-5">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ task.author }} | {{ task.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>
{% block footer %} {% include 'footer.html' %} {% endblock footer %}

{% endblock content %}